### ISSUE TITLE
因繁化姬的拼音轉換而造成的 "沒有這個音"

### ISSUE THREAD

**Issue by jfcherng** [EarlySpringCommitee/HowHow-web#11]
繁化姬的拼音輸出的是對岸的拼音方式，在某些情況下會使用 `v` 。

例如 `路` = `lu4` 、 `綠` = `lv4` 。所以 `綠` 將造成 `沒有這個音` 的情況。
同理 `努` = `nu3` 、 `女` = `nv3` 。所以 `女` 將造成 `沒有這個音` 的情況。

此專案目前遵照的[拼音表](https://www.lttc.ntu.edu.tw/GEPT1/Advanced/拼音對照表.pdf
)看起來和對岸的拼音一樣，但似乎 `ㄌㄨ` 、 `ㄌㄩ` 不分，都是 `lu` 。

![image](https://user-images.githubusercontent.com/6594915/83969537-280a9680-a903-11ea-9daa-f21660937a87.png) ![image](https://user-images.githubusercontent.com/6594915/83970354-eb8d6980-a907-11ea-8fb6-4dcdf4476853.png)

**Comment by gnehs** [comment]
你好，剛剛有更新發音了，還有什麼音標記錯誤嗎？

**Comment by jfcherng** [comment]
不知道，我並沒有使用，只是剛好看到。

**Comment by phlinhng** [comment]
應該要把 lv, nv, nve, lve 都修一下。
