### ISSUE TITLE
請問可否利用發音集製作好的音檔製作deepvocal聲庫？

### ISSUE THREAD

**Issue by ruoye030** [EarlySpringCommitee/HowHow-web#12]
HowHow發聲器的製作團隊們你們好！請問可否利用發音集製作好的音檔製作deepvocal聲庫？deepvocal也是一個免費的歌聲合成軟體，相較於UTAU的優勢是可以如同vocaloid可以即時播放，且界面與vocaloid較為相像
目前也在練習DV的聲庫製作(原音設定)，如果製作完成聲庫不會作販賣等商業行為，且可以分享給大眾:)

**Comment by gnehs** [comment]
基本上東西都開源了，根據 [MIT 授權條款](https://github.com/EarlySpringCommitee/HowHow-web/blob/master/LICENSE) 你要拿去幹嘛都可以，但不得進行 [商業用途](https://www.facebook.com/howfunofficial/posts/3243413899042874) 就是了
