### ISSUE TITLE
ㄏㄨㄟ(- ˊ ˇ ˋ) 的拼音標示錯誤(?)

### ISSUE THREAD

**Issue by t510599** [EarlySpringCommitee/HowHow-web#4]
這些檔案
- assets/audios/1/huei1.mp3
- assets/audios/1/huei2.mp3
- assets/audios/1/huei3.mp3
- assets/audios/1/huei4.mp3

根據繁化姬 拼音是 hui 而非 huei
![image](https://user-images.githubusercontent.com/18533304/83537635-6715a200-a527-11ea-944e-34444bf102d7.png)

**Comment by gnehs** [comment]
如果可以的話歡迎來直接修我們的發音表
https://docs.google.com/spreadsheets/d/1vWZ294BsgsTNEDJVBr5aDrvOWxg1FPi7d7-D0r5XrnY/edit?usp=sharing

**Comment by lekoOwO** [comment]
@t510599 我們的檔案是依據發音表構建的喔
不直接改發音表的話之後部署會被蓋掉

**Comment by t510599** [comment]
@gnehs @rexx0520
OK 去改了

**Comment by lekoOwO** [comment]
@gnehs 下一次構建的時候記得 fixed 這個 issue

**Comment by gnehs** [comment]
yay 他自己關ㄌ

**Comment by lekoOwO** [comment]
料料會用了 yay

**Comment by gnehs** [comment]
![sticker](https://user-images.githubusercontent.com/16719720/83541218-edcc7e00-a52b-11ea-93d6-0cd7d330bd9e.png)
